AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-hl7-parser

  Sample SAM Template for aws-lambda-hl7-parser

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  Hl7ReceiverFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hl7_receiver/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Hl7Receiver:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hl7-inbound
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Hl7ReceiverApi:
    Description: "API Gateway endpoint URL for Prod stage for Hl7 Receiver function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hl7-inbound/"
  Hl7ReceiverFunction:
    Description: "Hl7 Receiver Function ARN"
    Value: !GetAtt Hl7ReceiverFunction.Arn
  Hl7ReceiverFunctionIamRole:
    Description: "Implicit IAM Role created for Hl7 Receiver function"
    Value: !GetAtt Hl7ReceiverFunctionRole.Arn
